### PR TITLE
Cleanup for notifications-push

### PR DESCRIPTION
**Pull request by davidbalazs93**
Removed workaround code for Notifications Push.

*Note*: We will remove user-pwd for B2B clients from varnish authentication as well

### CODE REVIEW

**Comment by tosan88** [comment]
[Follow up - clean up](https://trello.com/c/5STjs6vJ/31-follow-up-clean-up)

**Comment by tamas-molnar** [comment]
This change removes throttling for B2B clients hitting the notifications-push endpoint - taking into consideration that they don't hit Mashery beforehand (which would throttle them), is this a good idea?

**Comment by tosan88** [comment]
Right, but the solution what we implemented due to Mashery's limitation of not supporting long polling makes it difficult to throttle such requests. 
Do you (or somebody else) have something in mind how could we throttle B2B without affecting Next? Or should we wait for Tyk to fix it? @lucas42 @sjwells ^^

**Comment by lucas42** [comment]
It doesn't look like Tyk is going to solve this any time soon.  
Now that we have API keys being sent, is there a way to throttle the number of open connections based on those?

**Comment by tosan88** [comment]
@lucas42 Do you have some concrete idea?  I only can think of hacking what Mashery would do and I would rather not introduce something that would be the responsibility of the API Gateway

**Comment by davidbalazs93** [comment]
lgtm

**Pull request merged**
