### PR TITLE
Adding lists to notifications push

### PR DESCRIPTION
**Pull request by peteclark-ft**

### CODE REVIEW

**Comment by galiri** [comment]
can't see to do a review approval so :+1:

**Comment by tosan88** [comment]
@galiri you have to be on the `Files changed` tab to see the `Review changes` button

**Comment by galiri** [comment]
@tosan88 I can see the button very well, pressing it  was a different matter,   thanks though

**Comment by peteclark-ft** [comment]
Thanks @galiri , @tosan88

**Comment by kovacshuni** [comment]
+1

**Pull request merged**
